In [30]:
import pandas as pd

In [31]:
with open('MNT_train_tags_adjusted_not_meaningful_strings_removed.txt', encoding='utf8') as infile:
    text1 = infile.read()
print(text1[:200])

Scott	<O>
rejects	<EVENT>
Bar	<O>
's	<O>
lists	<O>

Times	<O>
/	<O>
Herald	<O>
Tallahassee	<O>
Bureau	<O>

TALLAHASSEE	<O>
—	<O>
Gov.	<O>
Rick	<O>
Scott	<O>
,	<O>
seeking	<EVENT>
to	<O>
bring	<EVENT>

In [32]:
with open('TimeML_train_tags_adjusted_not_meaningful_strings_removed.txt', encoding='utf8') as infile:
    text2 = infile.read()
print(text2[:200])

Aetna	<O>
Life	<O>
amp	<O>
Casualty	<O>
Co.	<O>
's	<O>
third-quarter	<O>
net	<O>
income	<O>
fell	<EVENT>
22	<O>
%	<O>
to	<O>
$	<O>
182.6	<O>
million	<O>
,	<O>
or	<O>
$	<O>
1.63	<O>
a	<O>
share	<O>
,

In [33]:
text1 = text1.split('\n\n')
len(text1)

4292

In [34]:
def cleaning(sentence):
    sentence = sentence.replace(" n't", "n't")
    sentence = sentence.replace(" 's", "'s")
    sentence = sentence.replace(" 'm", "'m")
    sentence = sentence.replace(" 're", "'re")
    sentence = sentence.replace(" 've", "'ve")
    sentence = sentence.replace(" 'd", "'d")
    sentence = sentence.replace(" .", ".")
    sentence = sentence.replace(" ,", ",")
    sentence = sentence.replace(" !", "!")
    sentence = sentence.replace(" ?", "?")
    sentence = sentence.replace(" ;", ";")
    sentence = sentence.replace(" :", ":")
    sentence = sentence.replace("( ", "(")
    sentence = sentence.replace(" )", ")")        
    return sentence

In [35]:
def sentence_string(annotated_sentence):
    lines_of_annotated_sentence = annotated_sentence.split('\n')
    sentence = []
    for line in lines_of_annotated_sentence:
        splitline = line.split('\t')
        sentence.append(splitline[0])
    sentence_string = ' '.join(sentence)
    return cleaning(sentence_string)

In [36]:
def examples(list_of_annotated_sentences):
    examples = []
    for item in list_of_annotated_sentences:
        sentence = sentence_string(item)
        example = 'Sentence:\n' + sentence + '\n\n' + 'Annotated sentence:' + '\n\n' + item
        examples.append(example)
    return examples

In [37]:
ex1 = examples(text1)

In [61]:
print(ex1[1000])

Sentence:
B. IN SUMMARY OF THE RECENT WARNING STATING THAT SUCH AN ATTACK COULD BE EXECUTED IN THE VERY NEAR FUTURE HENSLER - HOBBS STATED THAT BIN LADEN 'S LOCATION WAS IRRELEVANT BECAUSE BIN LADEN POSSESSES THE MONEY AND SUPPORTERS NECESSARY TO HAVE SUCH AN ATTACK EXECUTED BY OTHERS.

Annotated sentence:

B.	<O>
IN	<O>
SUMMARY	<EVENT>
OF	<O>
THE	<O>
RECENT	<O>
WARNING	<EVENT>
STATING	<EVENT>
THAT	<O>
SUCH	<O>
AN	<O>
ATTACK	<EVENT>
COULD	<O>
BE	<O>
EXECUTED	<O>
IN	<O>
THE	<O>
VERY	<O>
NEAR	<O>
FUTURE	<O>
HENSLER	<O>
-	<O>
HOBBS	<O>
STATED	<EVENT>
THAT	<O>
BIN	<O>
LADEN	<O>
'S	<O>
LOCATION	<O>
WAS	<O>
IRRELEVANT	<EVENT>
BECAUSE	<O>
BIN	<O>
LADEN	<O>
POSSESSES	<EVENT>
THE	<O>
MONEY	<O>
AND	<O>
SUPPORTERS	<O>
NECESSARY	<O>
TO	<O>
HAVE	<O>
SUCH	<O>
AN	<O>
ATTACK	<EVENT>
EXECUTED	<O>
BY	<O>
OTHERS	<O>
.	<O>

In [62]:
text2 = text2.split('\n\n')
len(text2)

3855

In [63]:
ex2 = examples(text2)

In [67]:
print(ex2[1000])

Sentence:
And the weakness of the Asian economies is also likely to lead to decreased demand for American exports.

Annotated sentence:

And	<O>
the	<O>
weakness	<O>
of	<O>
the	<O>
Asian	<O>
economies	<O>
is	<O>
also	<O>
likely	<O>
to	<O>
lead	<EVENT>
to	<O>
decreased	<O>
demand	<O>
for	<O>
American	<O>
exports	<O>
.	<O>

In [68]:
df = pd.DataFrame({'example1_MNT': ex1[0:275], 'example2_MNT': ex1[275:550], 'example3_TimeML': ex2[0:275], 'example4_TimeML': ex2[275:550]})
df

,example1_MNT,example2_MNT,example3_TimeML,example4_TimeML
0,Sentence:\nScott rejects Bar's lists\n\nAnnota...,"Sentence:\nAs of Tuesday, Cuomo has given no c...",Sentence:\n Aetna Life amp Casualty Co.'s thir...,Sentence:\nThe earnings-per-share figures refl...
1,Sentence:\nTimes / Herald Tallahassee Bureau\n...,"Sentence:\nor pardons, in which convictions ar...",Sentence:\nCatastrophe losses reduced Aetna's ...,Sentence:\nMr. LeGere attributed the earnings ...
2,"Sentence:\nTALLAHASSEE — Gov. Rick Scott, seek...",Sentence:\nThat ’ s in contrast with the previ...,Sentence:\nLast year catastrophe losses totale...,Sentence:\nBillions of investors ' dollars are...
3,Sentence:\nScott has rejected dozens of attorn...,"Sentence:\nThe elder Cuomo, Eliot Spitzer and ...",Sentence:\nThe year-earlier results have been ...,"Sentence:\nLast week alone, an eye-popping $ 1..."
4,"Sentence:\n' ' He wants people with humility, ...",Sentence:\nAndrew Cuomo hasn ’ t closed the do...,Sentence:\nThe insurer has started processing ...,Sentence:\nIn the past two months the nation's...
...,...,...,...,...
270,"Sentence:\nReally sad news, this along with th...",Sentence:\nThe union also seemed eager to sett...,"Sentence:\nHowever, its value and benefits are...",Sentence:\n`` The tourism industry is very sen...
271,"Sentence:\nReally sad news, this along with th...",Sentence:\nBut Rodriguez has appealed his 211 ...,Sentence:\nChandler Insurance Co..\n\nAnnotate...,Sentence:\n`` We do expect a little downward m...
272,Sentence:\nand the Iraqi car bombing at the fu...,Sentence:\nGiven the volatility of the Rodrigu...,Sentence:\nsaid it expects to report third-qua...,Sentence:\nThe tourism industry in Kenya has b...
273,Sentence:\nGhost haunts pardon process\n\nAnno...,Sentence:\nFormer Pakistani dancing girl commi...,"Sentence:\nIn the year-earlier quarter, the au...",Sentence:\nTourism industry revenues reportedl...
274,"Sentence:\nALBANY, N.Y. – While Christmas mark...",Sentence:\nShe had undergone 39 separate surge...,"Sentence:\nIn an interview, W. Brent LeGere, c...",Sentence:\nThe government has responded to the...

In [69]:
df.to_csv('set_of_examples_for_TimeML.csv')

In [70]:
df2 = pd.DataFrame({'example1_MNT': ex1[0:1115], 'example2_MNT': ex1[1115:2230], 'example3_TimeML': ex2[0:1115], 'example4_TimeML': ex2[1115:2230]})
df2

,example1_MNT,example2_MNT,example3_TimeML,example4_TimeML
0,Sentence:\nScott rejects Bar's lists\n\nAnnota...,Sentence:\nTHE JAPANESE GOVERNMENT STATED ON A...,Sentence:\n Aetna Life amp Casualty Co.'s thir...,Sentence:\nCoast Savings Financial Inc..\n\nAn...
1,Sentence:\nTimes / Herald Tallahassee Bureau\n...,Sentence:\nTHIS WAS AFTER A SENIOR LAWMAKER SA...,Sentence:\nCatastrophe losses reduced Aetna's ...,"Sentence:\nreported a third-quarter loss, citi..."
2,"Sentence:\nTALLAHASSEE — Gov. Rick Scott, seek...",Sentence:\nBODY: 1.\n\nAnnotated sentence:\n\n...,Sentence:\nLast year catastrophe losses totale...,Sentence:\nThe Los Angeles thrift holding comp...
3,Sentence:\nScott has rejected dozens of attorn...,Sentence:\nTHE JAPANESE GOVERNMENT STATED ON A...,Sentence:\nThe year-earlier results have been ...,"Sentence:\nCoast earned $ 10.2 million, or 67 ..."
4,"Sentence:\n' ' He wants people with humility, ...",Sentence:\nTHIS WAS AFTER A SENIOR LAWMAKER SA...,Sentence:\nThe insurer has started processing ...,Sentence:\nThe year-ago results have been rest...
...,...,...,...,...
1110,Sentence:\nJAPAN (JP)\n\nAnnotated sentence:\n...,Sentence:\nOH rang me at 8pm as he does every ...,"Sentence:\nMarkets Stocks: Volume 170,330,000 ...",Sentence:\nThe U.S. government already has con...
1111,Sentence:\nTOPIC:\n\nAnnotated sentence:\n\nTO...,"Sentence:\nMany other items such as my laptop,...","Sentence:\nDow Jones industrials 2596.72, off ...","Sentence:\nOn Friday, the Kenyan government pl..."
1112,Sentence:\nPROLIFERATION;\n\nAnnotated sentenc...,Sentence:\nWe had returned from holiday the we...,Sentence:\nBonds: Shearson Lehman Hutton Treas...,Sentence:\nAVON RENT-A-CAR amp TRUCK Corp..\n\...
1113,Sentence:\nPOLITICS\n\nAnnotated sentence:\n\n...,Sentence:\nWe had been hearing stories when we...,Sentence:\nCommodities: Dow Jones futures inde...,Sentence:\nsaid it declared a dividend of one ...
1114,Sentence:\nSUMMARY:\n\nAnnotated sentence:\n\n...,Sentence:\nWe told the police this and explain...,"Sentence:\nDollar: 141.65 yen, off 0.45; 1.830...","Sentence:\nCurrently, Avon, based in Santa Mon..."

In [71]:
df2.to_csv('set_of_examples_for_MNT.csv')